openapi: 3.0.2
info:
  title: API
  version: 1.0.0
servers:
  - url: http://localhost:3100
components:
  schemas:
    CambiarEstadoOutput:
      type: object
      properties: 
        mensaje: 
          type: string
        datos: 
          type: object
          properties: 
            idIncidente: 
              type: integer
              format: int32
            estado: 
              type: string
            subestado: 
              type: string
              format: nullable
            fechaCreacion: 
              type: string
              format: date-time
            fechaRecepcion: 
              type: string
              format: nullable
            fechaFinalizacion: 
              type: string
              format: nullable

paths:
  /procesos/incidentes/cambiar-estado/{idIncidente}:
    patch:
      tags:
        - Procesos / Incidentes
      summary: Actualizar estado de incidente por ID
      parameters:
        - in: path
          name: idIncidente
          schema:
            type: integer
          required: true
          description: ID de incidete
      requestBody:
        required: true
        description: |
          - Valores de estado: [PENDIENTE, RECIBIDO, ASIGNADO, TERMINADO]
          - Valores de subestado cuando estado es TERMINADO: [ARCHIVADO, DERIVADO, DENUNCIADO, ATENDIDO], para los demás casos, es null.
        content:
          application/json:
            schema: 
              type: object
              properties:
                estado:
                  type: string
                  example: RECIBIDO
                subestado:
                  type: string
                  nullable: true
                  example: null

      responses:
        200:
          description: Actualizado correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CambiarEstadoOutput'
        404:
          description: ID no encontrado
        409:
          description: Atributo que debe ser único ya existe

  server:cambio-estado:
    options:
      tags:
        - Sockets / Incidentes
      summary: Recibir evento de cambio de estado (Web Monitor)
      description: "Modo de uso: `socket.on('server:cambio-estado', data => {})`"
      responses:
        200:
          description: Recibido correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  idIncidente:
                    type: number
                  estado:
                    type: string
                  subestado:
                    type: string
                  fechaCreacion:
                    type: string
                  fechaAsignacion:
                    type: string
                  fechaRecepcion:
                    type: string
                  fechaFinalizacion:
                    type: string
