version: "3.8"

services:
  database:
    image: mysql:8.2
    container_name: mysql-database
    restart: unless-stopped
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Admin2024
