openapi: 3.0.2
info:
  title: API
  version: 1.0.0
servers:
  - url: http://localhost:3100
components:
  schemas:
    ListarCentrosPobladosInput:
      type: object
      properties:
        idValor:
          type: integer
        texto:
          type: string
        estado:
          type: boolean
paths:
  /procesos/serenos/centros-poblados:
    get:
      tags:
        - Procesos / Serenos
      summary: Listar centros poblados
      responses:
        200:
          description: Listado correctamente
          # content:
          #   application/json:
          #     schema:
          #       $ref: '#/components/schemas/ListarCentrosPobladosOutput'
