openapi: 3.0.2
info:
  title: API
  version: 1.0.0
servers:
  - url: http://localhost:3100
paths:
  /incidentes/registrar-evento:
    post:
      tags:
        - Incidentes
      summary: Registrar un evento
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                idTipoIncidente:
                  description: ID del tipo de incidente
                  type: number
                  example: 1
                descripcion:
                  type: string
                  description: Descripción del evento
                  example: Incidente de prueba
                longitud:
                  type: string
                  description: Coordenada longitud del lugar evento
                  example: "-72.946554"
                latitud:
                  type: string
                  description: Coordenada latitud del lugar del evento
                  example: "-11.718343"
                archivos:
                  description: Lista de archivos por subir
                  type: array
                  items:
                    type: string
                    format: binary
              required:
                - descripcion
                - longitud
                - latitud
                - idTipoIncidente
      responses:
        200:
          description: Registros creados correctamente
          # content:
            # application/json:
            #   schema:
            #     type: object
            #     properties:
            #       mensaje: 
            #         type: string
        409:
          description: ID de registro ya se encuentra registrado
