openapi: 3.0.2
info:
  title: API
  version: 1.0.0
servers:
  - url: http://localhost:3301
paths:
  /procesos/incidentes/centros-poblados:
    get:
      tags:
        - Procesos / Incidentes
      summary: Listar centros poblados por orden alfabetico
      responses:
        200:
          description: Listado correctamente

