openapi: 3.0.2
info:
  title: API
  version: 1.0.0
servers:
  - url: http://localhost:3100
components:
  schemas:
    VerificarCodigoInput:
      type: object
      properties:
        opcion: 
          type: string
          example: correo
        destino: 
          type: string
          example: fagogad489@gekme.com
        codigoVerificacion: 
          type: string
          example: 423267
    VerificarCodigoOutput:
      type: object
      properties:
        mensaje: 
          type: string
          example: C贸digo verificado correctamente
        codigoValido: 
          type: boolean
          example: true

paths:
  /autenticacion/verificar-codigo:
    post:
      tags:
        - Autenticaci贸n
      summary: Validar c贸digo de verificaci贸n
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/VerificarCodigoInput'
            examples:
              Enviado por correo:
                value:
                  opcion: 'correo'
                  destino: 'test@test.com'
                  codigoVerificacion: 431241
              Enviado por sms:
                value:
                  opcion: 'sms'
                  destino: '987654321'
                  codigoVerificacion: 431241
      responses:
        200:
          description: Creado correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerificarCodigoOutput'
