export * from '@agente/features/personas/personas.repository'
export * from '@agente/features/usuarios/usuarios.repository'
export * from '@agente/features/perfiles/perfiles.repository'
export * from '@agente/features/archivos/archivos.repository'
export * from '@agente/features/serenos/serenos.repository'
export * from '@agente/features/centros-poblados/centros-poblados.repository'
