#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Go to project
cd ./app-ciudadano

# Get local branch name
local_branch_name="$(git rev-parse --abbrev-ref HEAD)"
echo $branch

# Avoid commits in main branch
if [ "$local_branch_name" = "main" ]; then
  echo "You can't commit directly to main branch."
  exit 1
fi

# Check branch name
valid_branch_regex='^((fix|feat)\/[a-zA-Z0-9\-]+)$'
if ! echo "$local_branch_name" | grep -qE "$valid_branch_regex"; then
  echo "There is something wrong with your branch name. Branch names in this project must adhere to this contract: $valid_branch_regex. Your commit will be rejected. You should rename your branch to a valid name and try again."
  exit 1
fi

# Run linting verification
if yarn lint; then
  echo "Linting passed successfully."
else
  echo "Linting failed. There are issues in your code. Please run 'yarn lint' to identify and fix the problems before committing."
  exit 1
fi

# Correct
exit 0
