openapi: 3.0.2
info:
  title: API
  version: 1.0.0
servers:
  - url: http://localhost:3100
# components:
  # schemas:
    # CrudIncidenteInput:
    #   type: object
    #   properties:
    #     idValor:
    #       type: integer
    #     texto:
    #       type: string
    #     estado:
    #       type: boolean
paths:
  /procesos/incidentes/listar:
    get:
      tags:
        - Procesos / Incidentes
      summary: Listar incidentes
      security: []
      responses:
        200:
          description: Listado correctamente
          # content:
          #   application/json:
          #     schema:
          #       $ref: '#/components/schemas/CrudIncidenteOutput'
