openapi: 3.0.2
info:
  title: API
  version: 1.0.0
servers:
  - url: http://localhost:3301
paths:
  /procesos/incidentes/listar:
    get:
      tags:
        - Procesos / Incidentes
      summary: Listar incidentes
      parameters:
        - in: query
          name: fechaInicio
          schema:
            type: string
          example: "2023-01-01"
          description: "Fecha de inicio. Valor por defecto: 2023-01-01"
        - in: query
          name: fechaFin
          schema:
            type: string
          example: "2100-12-31"
          description: "Fecha fin. Valor por defecto: 2100-12-31"
        - in: query
          name: estado
          schema:
            type: string
            enum: [PENDIENTE,RECIBIDO,ASIGNADO,TERMINADO]
          description: |
            Estado del incidente. Por defecto: Listar todos 
        - in: query
          name: idTipoIncidente
          schema:
            type: number
          description: |
            ID del tipo incidente. Por defecto: Listar todos

      responses:
        200:
          description: Listado correctamente
          # content:
          #   application/json:
          #     schema:
          #       $ref: '#/components/schemas/CrudIncidenteOutput'

