import type { MenuAcceso } from '../prisma-client'

type SubSistema = 'AppSerenazgo' | 'WebAdministracion'
type TipoModulo = 'proceso' | 'mantenimiento' | 'reporte' | 'configuracion'
type AmbitoAcceso = 'movil' | 'web' | 'mixto'
type Nivel = 1 | 2 | 3

interface TMenuAcceso
  extends Omit<MenuAcceso, 'subSistema' | 'tipoModulo' | 'ambitoAcceso' | 'nivel'> {
  subSistema: SubSistema
  tipoModulo: TipoModulo | null
  ambitoAcceso: AmbitoAcceso | null
  nivel: Nivel
}

export const menuAccesoSeed: TMenuAcceso[] = [
  // ################# ADMINISTRACION #################
  {
    menuCodigo: '010000',
    nombre: 'Administración',
    descripcion: 'Acceso al sistema de Administración',
    subSistema: 'WebAdministracion',
    nivel: 1,
    tipoModulo: null,
    ruta: null,
    icono: null,
    ambitoAcceso: 'web',
    mostrarEnMenu: false,
    estadoRegistro: true,
    fechaCreacion: new Date(),
    fechaModificacion: new Date(),
  },
  {
    menuCodigo: '010100',
    nombre: 'Procesos',
    descripcion: 'Acceder a procesos',
    subSistema: 'WebAdministracion',
    nivel: 2,
    tipoModulo: 'proceso',
    ruta: 'procesos',
    icono: null,
    ambitoAcceso: 'web',
    mostrarEnMenu: true,
    estadoRegistro: true,
    fechaCreacion: new Date(),
    fechaModificacion: new Date(),
  },
  {
    menuCodigo: '010101',
    nombre: 'Web monitor',
    descripcion: 'Ver web monitor',
    subSistema: 'WebAdministracion',
    nivel: 3,
    tipoModulo: 'proceso',
    ruta: 'incidentes',
    icono: null,
    ambitoAcceso: 'web',
    mostrarEnMenu: true,
    estadoRegistro: true,
    fechaCreacion: new Date(),
    fechaModificacion: new Date(),
  },
  {
    menuCodigo: '010200',
    nombre: 'Mantenimientos',
    descripcion: 'Acceder a mantenimientos',
    subSistema: 'WebAdministracion',
    nivel: 2,
    tipoModulo: 'mantenimiento',
    ruta: 'mantenimientos',
    icono: null,
    ambitoAcceso: 'web',
    mostrarEnMenu: true,
    estadoRegistro: true,
    fechaCreacion: new Date(),
    fechaModificacion: new Date(),
  },
  {
    menuCodigo: '010201',
    nombre: 'Usuarios',
    descripcion: 'Ver usuarios',
    subSistema: 'WebAdministracion',
    nivel: 3,
    tipoModulo: 'mantenimiento',
    ruta: 'usuarios',
    icono: null,
    ambitoAcceso: 'web',
    mostrarEnMenu: true,
    estadoRegistro: true,
    fechaCreacion: new Date(),
    fechaModificacion: new Date(),
  },
  {
    menuCodigo: '010202',
    nombre: 'Perfiles',
    descripcion: 'Ver perfiles',
    subSistema: 'WebAdministracion',
    nivel: 3,
    tipoModulo: 'mantenimiento',
    ruta: 'perfiles',
    icono: null,
    ambitoAcceso: 'web',
    mostrarEnMenu: true,
    estadoRegistro: true,
    fechaCreacion: new Date(),
    fechaModificacion: new Date(),
  },
  {
    menuCodigo: '010203',
    nombre: 'Ciudadanos',
    descripcion: 'Ver ciudadanos',
    subSistema: 'WebAdministracion',
    nivel: 3,
    tipoModulo: 'mantenimiento',
    ruta: 'ciudadanos',
    icono: null,
    ambitoAcceso: 'web',
    mostrarEnMenu: true,
    estadoRegistro: true,
    fechaCreacion: new Date(),
    fechaModificacion: new Date(),
  },
  // ------------------
  {
    menuCodigo: '010300',
    nombre: 'Reportes',
    descripcion: 'Acceder a reportes',
    subSistema: 'WebAdministracion',
    nivel: 2,
    tipoModulo: 'reporte',
    ruta: 'reportes',
    icono: null,
    ambitoAcceso: 'web',
    mostrarEnMenu: true,
    estadoRegistro: true,
    fechaCreacion: new Date(),
    fechaModificacion: new Date(),
  },
  {
    menuCodigo: '010301',
    nombre: 'Cronología de incidentes',
    descripcion: 'Ver cronología',
    subSistema: 'WebAdministracion',
    nivel: 3,
    tipoModulo: 'reporte',
    ruta: 'cronologia-eventos',
    icono: null,
    ambitoAcceso: 'web',
    mostrarEnMenu: true,
    estadoRegistro: true,
    fechaCreacion: new Date(),
    fechaModificacion: new Date(),
  },
  {
    menuCodigo: '010400',
    nombre: 'Configuraciones',
    descripcion: 'Acceder a configuraciones',
    subSistema: 'WebAdministracion',
    nivel: 2,
    tipoModulo: 'configuracion',
    ruta: 'configuraciones',
    icono: null,
    ambitoAcceso: 'web',
    mostrarEnMenu: true,
    estadoRegistro: true,
    fechaCreacion: new Date(),
    fechaModificacion: new Date(),
  },
  // ########### SERENAZGO ###########
  {
    menuCodigo: '020000',
    nombre: 'Serenazgo',
    descripcion: 'Acceso al sistema de Serenazgo',
    subSistema: 'AppSerenazgo',
    nivel: 1,
    tipoModulo: null,
    ruta: null,
    icono: null,
    ambitoAcceso: 'movil',
    mostrarEnMenu: false,
    estadoRegistro: true,
    fechaCreacion: new Date(),
    fechaModificacion: new Date(),
  },
  {
    menuCodigo: '020100',
    nombre: 'Procesos',
    descripcion: 'Acceder a procesos',
    subSistema: 'AppSerenazgo',
    nivel: 2,
    tipoModulo: 'proceso',
    ruta: 'procesos',
    icono: null,
    ambitoAcceso: 'movil',
    mostrarEnMenu: true,
    estadoRegistro: true,
    fechaCreacion: new Date(),
    fechaModificacion: new Date(),
  },
  {
    menuCodigo: '020101',
    nombre: 'Serenos',
    descripcion: 'Ver serenos',
    subSistema: 'AppSerenazgo',
    nivel: 3,
    tipoModulo: 'proceso',
    ruta: 'serenos',
    icono: null,
    ambitoAcceso: 'movil',
    mostrarEnMenu: false,
    estadoRegistro: true,
    fechaCreacion: new Date(),
    fechaModificacion: new Date(),
  },
  {
    menuCodigo: '020400',
    nombre: 'Configuraciones',
    descripcion: 'Acceder a configuraciones',
    subSistema: 'AppSerenazgo',
    nivel: 2,
    tipoModulo: 'configuracion',
    ruta: 'configuraciones',
    icono: null,
    ambitoAcceso: 'movil',
    mostrarEnMenu: true,
    estadoRegistro: true,
    fechaCreacion: new Date(),
    fechaModificacion: new Date(),
  },
]
