openapi: 3.0.2
info:
  title: API
  version: 1.0.0
servers:
  - url: http://localhost:3100
paths:
  server:nuevo-incidente:
    options:
      tags:
        - Sockets / Incidentes
      summary: Recibir evento de nuevo incidente reportado (Web Monitor)
      description: "Modo de uso: `socket.on('server:nuevo-incidente', data => {})`"
      responses:
        200:
          description: Recibido correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  idIncidente:
                    type: number
                  idDenunciante:
                    type: string
                  idTipoIncidente:
                    type: number
                  idCentroPoblado:
                    type: number
                  descripcion:
                    type: string
                  estado:
                    type: string
                  subestado:
                    type: string
                  longitud:
                    type: string
                  latitud:
                    type: string
                  fechaAsignacion:
                    type: string

