openapi: 3.0.2
info:
  title: API
  version: 1.0.0
servers:
  - url: http://localhost:3100
components:  
  schemas:
    EnviarCodigoInput:
      type: object
      properties:
        opcion: 
          type: string
        destino: 
          type: string
    EnviarCodigoOutput:
      type: object
      properties:
        mensaje: 
          type: string
          example: El c贸digo fue enviado correctamente

paths:
  /autenticacion/enviar-codigo:
    post:
      tags:
        - Autenticaci贸n
      summary: Enviar c贸digo de verificaci贸n
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/EnviarCodigoInput'          
            examples:
              Enviar por correo:
                value:
                  opcion: correo
                  destino: test@test.com
              Enviar por sms:
                value:
                  opcion: sms
                  destino: 987654321
      responses:
        200:
          description: Creado correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnviarCodigoOutput'
        400:
          description: Solicitud incorrecta
