openapi: 3.0.2
info:
  title: API
  version: 1.0.0
servers:
  - url: http://localhost:3100
components:
  schemas:
    ConsultaPersonaOutput:
      type: object
      properties:
        numeroDocumento: 
          type: string
        razonSocial: 
          type: string
        nombres: 
          type: string
        apellidoPaterno: 
          type: string
        apellidoMaterno: 
          type: string

paths:
  /servicios/persona/{nroDocumento}:
    get:
      tags:
        - Servicios
      summary: Buscar persona por Nro. de documento
      security: []
      parameters:
        - in: path
          name: nroDocumento
          schema:
            type: string
          required: true
          description: Número de documento de la persona
          examples:
            Busqueda por DNI: 
              value: 76543210
            Busqueda por RUC:
              value: 12345678910
        - in: header
          name: token
          schema:
            type: string
          required: true
          description: Token del servicio
      responses:
        200:
          description: Persona encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsultaPersonaOutput'
        404:
          description: Persona no encontrada

      
