openapi: 3.0.2
info:
  title: API
  version: 1.0.0
servers:
  - url: http://localhost:3100
components:
  schemas:
    ListarIncidentesInput:
      type: object
      properties:
        idValor:
          type: integer
        texto:
          type: string
        estado:
          type: boolean
paths:
  /procesos/serenos/listar-incidentes:
    get:
      tags:
        - Procesos / Serenos
      summary: Listar incidentes de un sereno
      parameters:
        - in: query
          name: tamanio
          schema:
            type: integer
          required: false
          description: "Número de incidentes a mostrar. Por defecto: 10"
        - in: query
          name: estado
          description: "Estado del incidente. Por defecto: Listar todos"
          schema:
            type: string
            enum: [PENDIENTE,RECIBIDO,ASIGNADO,TERMINADO]
      responses:
        200:
          description: Listado correctamente
          # content:
          #   application/json:
          #     schema:
          #       $ref: '#/components/schemas/ListarIncidentesOutput'
