openapi: 3.0.2
info:
  title: API
  version: 1.0.0
servers:
  - url: http://localhost:3100
# components:
  # schemas:
    # CrudIncidenteInput:
    #   type: object
    #   properties:
    #     idValor:
    #       type: integer
    #     texto:
    #       type: string
    #     estado:
    #       type: boolean
paths:

  /incidentes/listar-denunciados:
    get:
      tags:
        - Incidentes
      summary: Listar incidentes denunciados
      parameters:
        - in: query
          name: tamanio
          schema:
            type: number
          required: false
          description: "Número de elementos a mostrar. Por defecto: 5"
        - in: query
          name: estado
          schema:
            type: string
            enum: [PENDIENTE,RECIBIDO,ASIGNADO,TERMINADO]
          required: false
          description: "Estados del incidente. Por defecto: Listar todos"
      responses:
        200:
          description: OK
          # content:
          #   application/json:
          #     schema:
          #       $ref: '#/components/schemas/ListarEventosOutput'
        404:
          description: ID no encontrado
