// Generated by https://quicktype.io

export interface PersonaAPI {
  numeroDocumento: string
  razonSocial: string
  nombres: string | null
  apellidoPaterno: string | null
  apellidoMaterno: string | null
  fechaNacimiento: string | null
  sexo: string | null
  tipoDocumento: TipoDocumento
  tipoPersona: TipoPersona
  nacionalidad: Nacionalidad | null
  ubigeo: Ubigeo | null
}

export interface Nacionalidad {
  idNacionalidad: number
  codPlame: string
  pais: string
}

export interface TipoDocumento {
  idTipoDocumento: number
  desTipoDocumento: string
}

export interface TipoPersona {
  idTipoPersona: number
  desTipoPersona: string
}

export interface Ubigeo {
  codigoUbigeo: string
  distrito: string
  provincia: string
  departamento: string
  codDistrito: string
  codProvincia: string
  codDepartamento: string
}
