name: Deployment

run-name: Deployment from main branch made by @${{ github.actor }}

on:
  workflow_dispatch: # Deploy manually
  # push:
  #   branches: [ $default-branch ]
  # pull_request:
  #   branches: [ $default-branch ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Deploying changes
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/Desktop/alerta-seguridad/back
            git fetch
            git checkout main
            git pull

            yarn install
            yarn db:deploy:agente
            yarn db:deploy:ciudadano
            
            yarn build:agente
            yarn build:ciudadano

            pm2 reload ecosystem.config.js

            exit
