openapi: 3.0.2
info:
  title: API
  version: 1.0.0
servers:
  - url: http://localhost:3100
paths:
  /procesos/serenos/registrar-informe:
    post:
      tags:
        - Procesos / Serenos
      summary: Registrar un informe de incidente
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                idIncidente:
                  type: integer
                  description: Id del incidente
                idCentroPoblado:
                  type: integer
                  description: Id del centro poblado
                subestado:
                  type: string
                  description: |
                    Tipo de estado terminado
                    - ATENDIDO: Se solucionó el problema
                    - ARCHIVADO: No requería ninguna intervención
                    - DERIVADO: El caso fue designado a otro organismo de seguridad
                    - DENUNCIADO: El caso fue reportado 
                  enum: [ATENDIDO,ARCHIVADO,DERIVADO,DENUNCIADO]
                descripcion:
                  type: string
                  description: Descripción del evento
                archivos:
                  description: Lista de archivos por subir
                  type: array
                  items:
                    type: string
                    format: binary
              required:
                - idIncidente
                - idCentroPoblado
                - subestado
      responses:
        200:
          description: Registros creados correctamente
          content:
            application/json:
              schema:
                type: object
                properties: 
                  mensaje: 
                    type: string
                  datos: 
                    type: object
                    properties: 
                      idInforme: 
                        type: integer
                        format: int32
                      idIncidente: 
                        type: integer
                        format: int32
                      idSereno: 
                        type: string
                      descripcion: 
                        type: string
                      archivoDigital: 
                        type: array
                        items: 
                          type: object
                          properties: 
                            idIncidente: 
                              type: integer
                              format: int32
                            ruta: 
                              type: string
                            tipo: 
                              type: string
                            categoria: 
                              type: string

        409:
          description: ID de registro ya se encuentra registrado
